# Generated by Django 4.2.16 on 2026-05-12 19:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, default="", max_length=10)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                (
                    "symptoms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "existing_conditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("duration_days", models.IntegerField(blank=True, null=True)),
                ("free_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("awaiting_doctor_input", "Awaiting Doctor Input"),
                            ("generating_pdf", "Generating PDF"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("has_warning", models.BooleanField(default=False)),
                (
                    "warning_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnosis_jobs",
                        to="patients.patient",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diagnosis_jobs",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(max_length=512)),
                ("file_size_bytes", models.IntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="diagnosis.diagnosisjob",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="LLMReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[("claude", "Claude"), ("openai", "OpenAI")],
                        max_length=20,
                    ),
                ),
                ("llm_model", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("summary", models.TextField()),
                (
                    "differential_diagnosis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "recommended_investigations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "risk_factors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("raw_response", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_report",
                        to="diagnosis.diagnosisjob",
                    ),
                ),
            ],
            options={
                "db_table": "llm_reports",
            },
        ),
        migrations.CreateModel(
            name="JobError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_type", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                (
                    "sqs_message_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="diagnosis.diagnosisjob",
                    ),
                ),
            ],
            options={
                "db_table": "job_errors",
            },
        ),
        migrations.CreateModel(
            name="DoctorOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_opinion",
                        to="diagnosis.diagnosisjob",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_opinions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_opinions",
            },
        ),
        migrations.AddIndex(
            model_name="diagnosisjob",
            index=models.Index(
                fields=["patient", "submitted_at"], name="idx_diagnosis_patient"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosisjob",
            index=models.Index(fields=["status"], name="idx_diagnosis_status"),
        ),
        migrations.AddIndex(
            model_name="diagnosisjob",
            index=models.Index(fields=["submitted_by"], name="idx_diagnosis_submitter"),
        ),
    ]
