// design_doc §4.3 — GET /api/v1/diagnosis/{id}/ (polling) + PATCH /opinion/
// Polls until terminal status. Shows LLM report when ready.
// Clinician sees opinion form when status = awaiting_doctor_input.
// Shows PDF download button when status = completed.
import { useState, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { getDiagnosis, submitOpinion, type DiagnosisDetail } from '../api/diagnosisApi'
import { useAuth } from '../context/AuthContext'
import { usePolling } from '../hooks/usePolling'
import StatusBadge from '../components/StatusBadge'

// Polling stops when status leaves the "in-flight" states
const TERMINAL = new Set(['awaiting_doctor_input', 'completed', 'failed'])

export default function DiagnosisDetailPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { user } = useAuth()

  const [opinionText, setOpinionText] = useState('')
  const [opinionError, setOpinionError] = useState<string | null>(null)
  const [opinionLoading, setOpinionLoading] = useState(false)
  // After opinion is submitted, we re-poll until completed / failed
  const [opinionSubmitted, setOpinionSubmitted] = useState(false)

  // isDone: stop polling when status is in TERMINAL set OR when generating_pdf
  // (after opinion submission we want to keep polling through generating_pdf → completed)
  const isDone = useCallback((data: DiagnosisDetail) => {
    if (opinionSubmitted) {
      return data.status === 'completed' || data.status === 'failed'
    }
    return TERMINAL.has(data.status)
  }, [opinionSubmitted])

  const fetchFn = useCallback(() => {
    if (!id) return Promise.reject(new Error('No ID'))
    return getDiagnosis(id)
  }, [id])

  const { data, loading, error, restart } = usePolling<DiagnosisDetail>(fetchFn, isDone)

  async function handleOpinionSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!id) return
    setOpinionError(null)
    setOpinionLoading(true)
    try {
      await submitOpinion(id, opinionText)
      setOpinionSubmitted(true)
      // Restart polling to track generating_pdf → completed
      restart()
    } catch {
      setOpinionError('Failed to submit opinion. Please try again.')
    } finally {
      setOpinionLoading(false)
    }
  }

  if (loading && !data) {
    return <PageShell><p style={{ padding: '2rem' }}>Loading diagnosis…</p></PageShell>
  }

  if (error) {
    return <PageShell><div style={styles.errorBox}>{error}</div></PageShell>
  }

  if (!data) return null

  const canSubmitOpinion =
    user?.role === 'clinician' &&
    data.status === 'awaiting_doctor_input' &&
    !opinionSubmitted

  return (
    <PageShell>
      {/* Header row */}
      <div style={styles.headerRow}>
        <div>
          <h2 style={styles.heading}>Diagnosis Detail</h2>
          <code style={styles.diagId}>{data.diagnosis_id}</code>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <StatusBadge status={data.status} />
          <button style={styles.backBtn} onClick={() => navigate('/')}>← Back</button>
        </div>
      </div>

      <p style={styles.meta}>
        Submitted: {new Date(data.submitted_at).toLocaleString()}
      </p>

      {/* Polling spinner for in-flight states */}
      {(data.status === 'pending' || data.status === 'processing' || data.status === 'generating_pdf') && (
        <div style={styles.infoBox}>
          ⏳ {data.status === 'generating_pdf'
            ? 'Generating PDF report…'
            : 'LLM analysis in progress. Page updates automatically every 3 seconds.'}
        </div>
      )}

      {/* LLM Report */}
      {data.llm_report && (
        <section style={styles.card}>
          <h3 style={styles.cardTitle}>LLM Analysis Report</h3>
          <p style={styles.meta}>
            Generated by <strong>{data.llm_report.generated_by}</strong> at{' '}
            {new Date(data.llm_report.generated_at).toLocaleString()}
          </p>

          <h4 style={styles.h4}>Summary</h4>
          <p>{data.llm_report.summary}</p>

          <h4 style={styles.h4}>Differential Diagnosis</h4>
          <ul>{data.llm_report.differential_diagnosis.map((d, i) => <li key={i}>{d}</li>)}</ul>

          <h4 style={styles.h4}>Recommended Investigations</h4>
          <ul>{data.llm_report.recommended_investigations.map((r, i) => <li key={i}>{r}</li>)}</ul>

          <h4 style={styles.h4}>Risk Factors</h4>
          <ul>{data.llm_report.risk_factors.map((r, i) => <li key={i}>{r}</li>)}</ul>
        </section>
      )}

      {/* Doctor opinion (read-only once submitted) */}
      {data.doctor_opinion && (
        <section style={styles.card}>
          <h3 style={styles.cardTitle}>Doctor's Opinion</h3>
          <p style={styles.meta}>
            Submitted by <strong>{data.doctor_opinion.submitted_by}</strong> at{' '}
            {new Date(data.doctor_opinion.submitted_at).toLocaleString()}
          </p>
          <p>{data.doctor_opinion.text}</p>
        </section>
      )}

      {/* Opinion form — only for the submitting Clinician */}
      {canSubmitOpinion && (
        <section style={styles.card}>
          <h3 style={styles.cardTitle}>Submit Your Opinion</h3>
          {opinionError && <div style={styles.errorBox}>{opinionError}</div>}
          <form onSubmit={handleOpinionSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <textarea
              style={styles.textarea}
              required
              rows={5}
              placeholder="Enter your clinical diagnosis and treatment plan…"
              value={opinionText}
              onChange={e => setOpinionText(e.target.value)}
            />
            <button style={styles.submitBtn} type="submit" disabled={opinionLoading}>
              {opinionLoading ? 'Submitting…' : 'Submit Opinion & Generate PDF'}
            </button>
          </form>
        </section>
      )}

      {/* PDF download — status=completed */}
      {data.status === 'completed' && (
        <section style={styles.card}>
          <h3 style={styles.cardTitle}>Report Ready</h3>
          <button
            style={styles.downloadBtn}
            onClick={() => navigate(`/diagnosis/${data.diagnosis_id}/report`)}
          >
            📄 Download PDF Report
          </button>
        </section>
      )}

      {data.status === 'failed' && (
        <div style={styles.errorBox}>
          This diagnosis task failed. Please contact support or resubmit.
        </div>
      )}
    </PageShell>
  )
}

function PageShell({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate()
  return (
    <div style={{ minHeight: '100vh', background: '#f4f6f9', fontFamily: 'sans-serif' }}>
      <header style={styles.nav}>
        <span style={{ fontWeight: 700, fontSize: '1.1rem' }}>AI Diagnosis System</span>
        <button style={styles.backBtn} onClick={() => navigate('/')}>← Back to List</button>
      </header>
      <main style={styles.main}>{children}</main>
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  nav: {
    background: '#2c3e50', color: '#fff', padding: '12px 24px',
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  },
  main: { maxWidth: '800px', margin: '0 auto', padding: '24px' },
  heading: { margin: '0 0 4px', color: '#2c3e50' },
  diagId: { fontSize: '0.78rem', color: '#7f8c8d' },
  meta: { fontSize: '0.88rem', color: '#7f8c8d', margin: '0 0 8px' },
  headerRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
    marginBottom: '8px',
  },
  card: {
    background: '#fff', borderRadius: '8px', padding: '20px',
    marginBottom: '16px', boxShadow: '0 1px 4px rgba(0,0,0,0.07)',
  },
  cardTitle: { margin: '0 0 10px', fontSize: '1rem', color: '#2c3e50' },
  h4: { margin: '14px 0 4px', color: '#34495e', fontSize: '0.93rem' },
  infoBox: {
    background: '#eaf4fb', border: '1px solid #85c1e9',
    borderRadius: '6px', padding: '12px 16px', marginBottom: '16px',
    color: '#1a6fa1', fontSize: '0.92rem',
  },
  errorBox: {
    background: '#fdecea', color: '#c0392b', border: '1px solid #f5c6cb',
    borderRadius: '6px', padding: '10px 14px', marginBottom: '16px',
  },
  textarea: {
    padding: '10px 12px', border: '1px solid #dce1e7',
    borderRadius: '6px', fontSize: '0.93rem', resize: 'vertical',
  },
  submitBtn: {
    padding: '10px 20px', background: '#27ae60', color: '#fff',
    border: 'none', borderRadius: '6px', fontSize: '0.95rem',
    fontWeight: 600, cursor: 'pointer', alignSelf: 'flex-start',
  },
  downloadBtn: {
    padding: '12px 24px', background: '#3498db', color: '#fff',
    border: 'none', borderRadius: '8px', fontSize: '1rem',
    fontWeight: 600, cursor: 'pointer',
  },
  backBtn: {
    background: 'transparent', color: '#bdc3c7', border: '1px solid #7f8c8d',
    borderRadius: '6px', padding: '5px 12px', cursor: 'pointer',
  },
}
